# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/env_extr_clock.xdc

# XDC: imports/sysgen/env_extr.xdc

# Block Designs: bd/env_extr_bd/env_extr_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_bd || ORIG_REF_NAME==env_extr_bd} -quiet] -quiet

# IP: bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_bd_env_extr_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_bd_env_extr_1_0 || ORIG_REF_NAME==env_extr_bd_env_extr_1_0} -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/env_extr_bd_ooc.xdc
