# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.srcs/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_bd_env_extr_1_0.xci
# IP: The module: 'env_extr_bd_env_extr_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i0/env_extr_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i0 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i1/env_extr_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i1 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i10/env_extr_c_addsub_v12_0_i10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i10 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i10} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i11/env_extr_c_addsub_v12_0_i11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i11 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i11} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i12/env_extr_c_addsub_v12_0_i12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i12 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i12} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i13/env_extr_c_addsub_v12_0_i13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i13 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i13} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i14/env_extr_c_addsub_v12_0_i14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i14 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i14} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i15/env_extr_c_addsub_v12_0_i15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i15 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i15} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i16/env_extr_c_addsub_v12_0_i16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i16 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i16} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i2/env_extr_c_addsub_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i2 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i3/env_extr_c_addsub_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i3 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i4/env_extr_c_addsub_v12_0_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i4 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i5/env_extr_c_addsub_v12_0_i5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i5 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i5} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i6/env_extr_c_addsub_v12_0_i6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i6 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i6} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i7/env_extr_c_addsub_v12_0_i7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i7 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i7} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i8/env_extr_c_addsub_v12_0_i8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i8 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i8} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i9/env_extr_c_addsub_v12_0_i9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i9 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i9} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_counter_binary_v12_0_i0/env_extr_c_counter_binary_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==env_extr_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_counter_binary_v12_0_i1/env_extr_c_counter_binary_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==env_extr_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_counter_binary_v12_0_i2/env_extr_c_counter_binary_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_counter_binary_v12_0_i2 || ORIG_REF_NAME==env_extr_c_counter_binary_v12_0_i2} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_counter_binary_v12_0_i3/env_extr_c_counter_binary_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_counter_binary_v12_0_i3 || ORIG_REF_NAME==env_extr_c_counter_binary_v12_0_i3} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_counter_binary_v12_0_i4/env_extr_c_counter_binary_v12_0_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_counter_binary_v12_0_i4 || ORIG_REF_NAME==env_extr_c_counter_binary_v12_0_i4} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_counter_binary_v12_0_i5/env_extr_c_counter_binary_v12_0_i5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_counter_binary_v12_0_i5 || ORIG_REF_NAME==env_extr_c_counter_binary_v12_0_i5} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_cordic_v6_0_i0/env_extr_cordic_v6_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_cordic_v6_0_i0 || ORIG_REF_NAME==env_extr_cordic_v6_0_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_cordic_v6_0_i1/env_extr_cordic_v6_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_cordic_v6_0_i1 || ORIG_REF_NAME==env_extr_cordic_v6_0_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i0/env_extr_fifo_generator_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i0 || ORIG_REF_NAME==env_extr_fifo_generator_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i1/env_extr_fifo_generator_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i1 || ORIG_REF_NAME==env_extr_fifo_generator_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i2/env_extr_fifo_generator_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i2 || ORIG_REF_NAME==env_extr_fifo_generator_i2} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i3/env_extr_fifo_generator_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i3 || ORIG_REF_NAME==env_extr_fifo_generator_i3} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i0/env_extr_fir_compiler_v7_2_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i0 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i1/env_extr_fir_compiler_v7_2_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i1 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i2/env_extr_fir_compiler_v7_2_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i2 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i2} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i3/env_extr_fir_compiler_v7_2_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i3 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i3} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i4/env_extr_fir_compiler_v7_2_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i4 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i4} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i5/env_extr_fir_compiler_v7_2_i5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i5 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i5} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i6/env_extr_fir_compiler_v7_2_i6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i6 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i6} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i0/env_extr_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i0 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i1/env_extr_mult_gen_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i1 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i10/env_extr_mult_gen_v12_0_i10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i10 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i10} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i11/env_extr_mult_gen_v12_0_i11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i11 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i11} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i12/env_extr_mult_gen_v12_0_i12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i12 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i12} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i13/env_extr_mult_gen_v12_0_i13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i13 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i13} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i14/env_extr_mult_gen_v12_0_i14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i14 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i14} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i15/env_extr_mult_gen_v12_0_i15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i15 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i15} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i16/env_extr_mult_gen_v12_0_i16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i16 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i16} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i17/env_extr_mult_gen_v12_0_i17.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i17 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i17} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i18/env_extr_mult_gen_v12_0_i18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i18 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i18} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i19/env_extr_mult_gen_v12_0_i19.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i19 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i19} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i2/env_extr_mult_gen_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i2 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i2} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i3/env_extr_mult_gen_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i3 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i3} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i4/env_extr_mult_gen_v12_0_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i4 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i4} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i5/env_extr_mult_gen_v12_0_i5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i5 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i5} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i6/env_extr_mult_gen_v12_0_i6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i6 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i6} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i7/env_extr_mult_gen_v12_0_i7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i7 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i7} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i8/env_extr_mult_gen_v12_0_i8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i8 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i8} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i9/env_extr_mult_gen_v12_0_i9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i9 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i9} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_xfft_v9_1_i0/env_extr_xfft_v9_1_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_xfft_v9_1_i0 || ORIG_REF_NAME==env_extr_xfft_v9_1_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_xfft_v9_1_i1/env_extr_xfft_v9_1_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_xfft_v9_1_i1 || ORIG_REF_NAME==env_extr_xfft_v9_1_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_xfft_v9_1_i2/env_extr_xfft_v9_1_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_xfft_v9_1_i2 || ORIG_REF_NAME==env_extr_xfft_v9_1_i2} -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i0/env_extr_fifo_generator_i0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i0 || ORIG_REF_NAME==env_extr_fifo_generator_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i1/env_extr_fifo_generator_i1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i1 || ORIG_REF_NAME==env_extr_fifo_generator_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i2/env_extr_fifo_generator_i2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i2 || ORIG_REF_NAME==env_extr_fifo_generator_i2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i3/env_extr_fifo_generator_i3.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i3 || ORIG_REF_NAME==env_extr_fifo_generator_i3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i0 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i1/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i1 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i2/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i2 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i3/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i3 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i4/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i4 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i5/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i5 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i5} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i6/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i6 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i6} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/constrs/env_extr.xdc
# XDC: The top module name and the constraint reference have the same name: 'env_extr_bd_env_extr_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.srcs/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_bd_env_extr_1_0.xci
# IP: The module: 'env_extr_bd_env_extr_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i0/env_extr_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i0 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i1/env_extr_c_addsub_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i1 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i10/env_extr_c_addsub_v12_0_i10.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i10 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i10} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i11/env_extr_c_addsub_v12_0_i11.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i11 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i11} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i12/env_extr_c_addsub_v12_0_i12.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i12 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i12} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i13/env_extr_c_addsub_v12_0_i13.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i13 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i13} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i14/env_extr_c_addsub_v12_0_i14.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i14 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i14} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i15/env_extr_c_addsub_v12_0_i15.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i15 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i15} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i16/env_extr_c_addsub_v12_0_i16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i16 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i16} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i2/env_extr_c_addsub_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i2 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i3/env_extr_c_addsub_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i3 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i4/env_extr_c_addsub_v12_0_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i4 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i5/env_extr_c_addsub_v12_0_i5.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i5 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i5} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i6/env_extr_c_addsub_v12_0_i6.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i6 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i6} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i7/env_extr_c_addsub_v12_0_i7.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i7 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i7} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i8/env_extr_c_addsub_v12_0_i8.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i8 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i8} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_addsub_v12_0_i9/env_extr_c_addsub_v12_0_i9.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_addsub_v12_0_i9 || ORIG_REF_NAME==env_extr_c_addsub_v12_0_i9} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_counter_binary_v12_0_i0/env_extr_c_counter_binary_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==env_extr_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_counter_binary_v12_0_i1/env_extr_c_counter_binary_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==env_extr_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_counter_binary_v12_0_i2/env_extr_c_counter_binary_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_counter_binary_v12_0_i2 || ORIG_REF_NAME==env_extr_c_counter_binary_v12_0_i2} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_counter_binary_v12_0_i3/env_extr_c_counter_binary_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_counter_binary_v12_0_i3 || ORIG_REF_NAME==env_extr_c_counter_binary_v12_0_i3} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_counter_binary_v12_0_i4/env_extr_c_counter_binary_v12_0_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_counter_binary_v12_0_i4 || ORIG_REF_NAME==env_extr_c_counter_binary_v12_0_i4} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_c_counter_binary_v12_0_i5/env_extr_c_counter_binary_v12_0_i5.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_c_counter_binary_v12_0_i5 || ORIG_REF_NAME==env_extr_c_counter_binary_v12_0_i5} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_cordic_v6_0_i0/env_extr_cordic_v6_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_cordic_v6_0_i0 || ORIG_REF_NAME==env_extr_cordic_v6_0_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_cordic_v6_0_i1/env_extr_cordic_v6_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_cordic_v6_0_i1 || ORIG_REF_NAME==env_extr_cordic_v6_0_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i0/env_extr_fifo_generator_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i0 || ORIG_REF_NAME==env_extr_fifo_generator_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i1/env_extr_fifo_generator_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i1 || ORIG_REF_NAME==env_extr_fifo_generator_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i2/env_extr_fifo_generator_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i2 || ORIG_REF_NAME==env_extr_fifo_generator_i2} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i3/env_extr_fifo_generator_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i3 || ORIG_REF_NAME==env_extr_fifo_generator_i3} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i0/env_extr_fir_compiler_v7_2_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i0 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i1/env_extr_fir_compiler_v7_2_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i1 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i2/env_extr_fir_compiler_v7_2_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i2 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i2} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i3/env_extr_fir_compiler_v7_2_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i3 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i3} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i4/env_extr_fir_compiler_v7_2_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i4 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i4} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i5/env_extr_fir_compiler_v7_2_i5.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i5 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i5} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i6/env_extr_fir_compiler_v7_2_i6.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i6 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i6} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i0/env_extr_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i0 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i1/env_extr_mult_gen_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i1 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i10/env_extr_mult_gen_v12_0_i10.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i10 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i10} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i11/env_extr_mult_gen_v12_0_i11.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i11 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i11} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i12/env_extr_mult_gen_v12_0_i12.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i12 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i12} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i13/env_extr_mult_gen_v12_0_i13.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i13 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i13} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i14/env_extr_mult_gen_v12_0_i14.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i14 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i14} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i15/env_extr_mult_gen_v12_0_i15.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i15 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i15} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i16/env_extr_mult_gen_v12_0_i16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i16 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i16} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i17/env_extr_mult_gen_v12_0_i17.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i17 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i17} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i18/env_extr_mult_gen_v12_0_i18.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i18 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i18} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i19/env_extr_mult_gen_v12_0_i19.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i19 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i19} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i2/env_extr_mult_gen_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i2 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i2} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i3/env_extr_mult_gen_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i3 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i3} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i4/env_extr_mult_gen_v12_0_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i4 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i4} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i5/env_extr_mult_gen_v12_0_i5.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i5 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i5} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i6/env_extr_mult_gen_v12_0_i6.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i6 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i6} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i7/env_extr_mult_gen_v12_0_i7.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i7 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i7} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i8/env_extr_mult_gen_v12_0_i8.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i8 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i8} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_mult_gen_v12_0_i9/env_extr_mult_gen_v12_0_i9.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_mult_gen_v12_0_i9 || ORIG_REF_NAME==env_extr_mult_gen_v12_0_i9} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_xfft_v9_1_i0/env_extr_xfft_v9_1_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_xfft_v9_1_i0 || ORIG_REF_NAME==env_extr_xfft_v9_1_i0} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_xfft_v9_1_i1/env_extr_xfft_v9_1_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_xfft_v9_1_i1 || ORIG_REF_NAME==env_extr_xfft_v9_1_i1} -quiet] -quiet

# IP: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_xfft_v9_1_i2/env_extr_xfft_v9_1_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==env_extr_xfft_v9_1_i2 || ORIG_REF_NAME==env_extr_xfft_v9_1_i2} -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i0/env_extr_fifo_generator_i0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i0 || ORIG_REF_NAME==env_extr_fifo_generator_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i1/env_extr_fifo_generator_i1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i1 || ORIG_REF_NAME==env_extr_fifo_generator_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i2/env_extr_fifo_generator_i2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i2 || ORIG_REF_NAME==env_extr_fifo_generator_i2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fifo_generator_i3/env_extr_fifo_generator_i3.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fifo_generator_i3 || ORIG_REF_NAME==env_extr_fifo_generator_i3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i0 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i1/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i1 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i2/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i2 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i3/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i3 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i4/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i4 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i5/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i5 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i5} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/env_extr_fir_compiler_v7_2_i6/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==env_extr_fir_compiler_v7_2_i6 || ORIG_REF_NAME==env_extr_fir_compiler_v7_2_i6} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/windows/Desktop/HSS/Q16_40840_optim/code2/ip/env_extr/src/ip_catalog/env_extr.gen/sources_1/bd/env_extr_bd/ip/env_extr_bd_env_extr_1_0/constrs/env_extr.xdc
# XDC: The top module name and the constraint reference have the same name: 'env_extr_bd_env_extr_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
